name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]   # Trigger on push to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-python-app:latest -f pipeline-practice/Dockerfile pipeline-practice/

      
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-python-app:latest

